server:
  port: 8080
spring:
  application:
    name: etl
  datasource:
    url: 'jdbc:mysql://192.168.37.110:3306/prod_spider'
    username: 'zl-test'
    password: 'zl@2020'

logging:
  file:
    path: @project.basedir@/log